import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/modules/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className="text-red-0">koksze</h1>
        <Navbar>
          <Navbar.NavbarItem visibility="both">LOGO</Navbar.NavbarItem>
          <Navbar.Group>
            <Navbar.NavbarGroupItem visibility="both">
              MOVIES
            </Navbar.NavbarGroupItem>
            <Navbar.NavbarGroupItem visibility="both">
              ACTORS
            </Navbar.NavbarGroupItem>
          </Navbar.Group>
        </Navbar>
        {children}
      </body>
    </html>
  );
}
