import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/modules/Navbar/Navbar";
import { Text } from "@/modules/Text/Text";
import { Link } from "@/modules/ui/Button/Link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mb-12">
          <Navbar>
            <Navbar.Group>
              <Navbar.NavbarGroupItem visibility="both">
                <Link href="/">LOGO</Link>
              </Navbar.NavbarGroupItem>
              <Navbar.NavbarGroupItem visibility="both">
                <Text>CREATE AN ACCOUNT</Text>
              </Navbar.NavbarGroupItem>
              <Navbar.NavbarGroupItem visibility="both">
                <Text>LOG IN</Text>
              </Navbar.NavbarGroupItem>
            </Navbar.Group>
          </Navbar>
        </div>
        {children}
      </body>
    </html>
  );
}
